### ISSUE TITLE
Add support for GoldSrc responses

### ISSUE THREAD

**Issue by k0st1an** [serverstf/python-valve#30]
Example: [doc](http://python-valve.readthedocs.org/en/latest/source.html#example)
Error at **info = server.info()**

```
Traceback (most recent call last):
  File "./test.py", line 9, in <module>
    info = server.info()
  File "/home/kruglov/.virtualenvs/py-valve/local/lib/python2.7/site-packages/valve/source/a2s.py", line 156, in info
    return messages.InfoResponse.decode(self.get_response())
  File "/home/kruglov/.virtualenvs/py-valve/local/lib/python2.7/site-packages/valve/source/messages.py", line 415, in decode
    values[field.name], buffer = field.decode(buffer, values)
  File "/home/kruglov/.virtualenvs/py-valve/local/lib/python2.7/site-packages/valve/source/messages.py", line 41, in needs_buffer
    return func(self, buffer, *args, **kwargs)
  File "/home/kruglov/.virtualenvs/py-valve/local/lib/python2.7/site-packages/valve/source/messages.py", line 131, in decode
    struct.unpack(self.format, field_data)[0]), left_overs)
  File "/home/kruglov/.virtualenvs/py-valve/local/lib/python2.7/site-packages/valve/source/messages.py", line 95, in validate
    value, self.name))
valve.source.messages.BrokenMessageError: Invalid value (109) for field 'response_type'
```

**Comment by lovelydev** [comment]
Yep, can't get it working because of this error :(

**Comment by darkchemist** [comment]
I am also having a similar error with the same example code: 
`Traceback (most recent call last):
  File "/Users/*****/PycharmProjects/steam_master_server_query/servertest.py", line 10, in <module>
    info = server.info()
AttributeError: 'ServerQuerier' object has no attribute 'info'`

**Comment by VatsalP** [comment]
Installing using setup.py from git repo rather than pip solves this.

**Comment by vigilancer** [comment]
seems `109` (or `x6D`) is code for InfoResponse from `Obsolete GoldSource` servers.  
https://developer.valvesoftware.com/wiki/Server_queries#Request_Format
not sure how this info makes any good without adding support for this into library.


anyway, in my case _every second_ request failing with `valve.source.messages.BrokenMessageError: Invalid value (109) for field 'response_type'`.
surprisingly, every first gives me info without errors. guess I'll just query it twice, but still problem exists.

**Comment by vigilancer** [comment]
@darkchemist 
no, this is not the same issue.

@VatsalP 
are you sure you had same issue? failing to see how installation method can possibly fix response code support.

**Comment by Yepoleb** [comment]
Can you provide a server address or at least a game name so I can try to reproduce this?

**Comment by lxnch** [comment]
Here's one:

```
from valve.source.a2s import ServerQuerier
address=("89.44.246.23",27015)
with ServerQuerier(address) as server:
    print(server.info())
```

**Comment by Yepoleb** [comment]
@lxnch I just tested with this address and the info request works for me, the player request doesn't, but that seems to be a server side implementation error. Unfortunately it's not related to the original issue. Thank you for submitting the example though!

**Comment by Yepoleb** [comment]
I was able to confirm that the server in question returns a 109 response, which is not handled correctly. This is to be expected from a CounterStrike server, as it runs on the older GoldSrc engine, which is currently not supported by this library. But while this is working as intended, I think adding support for GoldSrc responses should not be too difficult for the increase in compatibility it provides.

**Comment by Yepoleb** [comment]
I've added support for GoldSrc in [python-a2s](https://github.com/Yepoleb/python-a2s)
