### ISSUE TITLE
Support Python 3.4, 3.5 and 3.6

### ISSUE THREAD

**Issue by Holiverh** [serverstf/python-valve#7]
Support will be added for Python 3 -- 3.4 and up to be specific -- via [six](https://pythonhosted.org/six/). `valve.source` will be ported forward as that actually has test coverage. The rest will pretty much be rewritten from scratch.

**CI for Python 3.4 support**: https://travis-ci.org/Holiverh/python-valve

**Comment by flubbateios** [comment]
the CI for the 3.4 support is down

**Comment by Holiverh** [comment]
You're quite right. It's best to look at Travis these days: https://travis-ci.org/Holiverh/python-valve

Note that the functional tests are not run on Travis. And there's also not 100% coverage so a pass may not strictly indicate that everything actually works with Python 3.4.

**Comment by flubbateios** [comment]
I don't know if I should create a new issue for this, but i'm having some issues with the rcon.
I keep getting the error
NameError: name 'unicode' is not defined

http://pastebin.com/Y8WAZVTH code and full error.
I don't know the version, but I just clicked download zip, and installed the module.

Do you know what the problem could be?

**Comment by Holiverh** [comment]
It's a straight up Python 3 incompatible section of the current RCON implementation. Luckily for you I'm [actively working on a new version]() which is currently in a somewhat usable state -- especially for Python 3.4.

So I'd reccomend trying that branch out: https://github.com/Holiverh/python-valve/archive/rcon-rewrite.zip

Note that the new version does change the API (not too dramatically), but you should get the idea just from looking at the code and docstrings.
