### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by InfernalPlacebo** [serverstf/python-valve#82]
I am just wondering if this project is being maintained. The last commit was 10 months ago. I just want to know if it is worth investing time incorporating this into my project or if I should move to something else.

**Comment by Yepoleb** [comment]
Not really, the owner has disappeared for a while now and I don't feel comfortable taking over and merging all my changes. Maybe I'll fork it in the next few days and publish my own package, so things finally get moving again.

**Comment by InfernalPlacebo** [comment]
That is what I was thinking happened.... I was considering forking it if that was going to be the case. If/when you fork it can you let me know?

**Comment by Yepoleb** [comment]
Sure, I'll leave a comment.

**Comment by Yepoleb** [comment]
I didn't want to leave you hanging, so I started working on a rewrite :smile:. You can follow the development here: https://github.com/Yepoleb/python-a2s

**Comment by InfernalPlacebo** [comment]
Thank you! 💃 I watched the repo and will continue the conversation over there :)
